config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  # root "jobs#index"
  devise_scope :user do
    root "devise/sessions#new"
  end  
  resources :clients
  resources :jobs
  resources :profiles
  # resources :applies
  get "new_application", to: "applies#new_apply"
  resources :applies do
    member do
      get 'accept'
      get 'reject'
    end
  end

  # post "new_application", to: "applies#new_apply"
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    if user.client?
      can :create, Job
      can :read, Job
      can :update, Job do |job|
        user.jobs.include?(job)
      end
      can :destroy, Job, user: user
      can [:read, :accept, :reject], Apply, job: { user_id: user.id }
    elsif user.applicant?
      can :read, Job
      can [:destroy, :new_apply, :read], Apply, user_id: user.id
      can :update, Profile, user: user
      can :create, Profile
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/apply.rb
class Apply < ApplicationRecord
  paginates_per 5
  belongs_to :job
  belongs_to :applicant, :class_name => "User", foreign_key: 'user_id'
  enum :status, {hold: 0, accepted:1, rejected: 2}
  after_create :send_job_mail


  def send_job_mail
    user = User.find(self.user_id)
    job = self.job
    ConfirmationMailer.with(user: user,job: job).application_email.deliver_now
  end

  def send_accept_mail
    user = User.find(self.user_id)
    job = self.job
    ConfirmationMailer.with(user: user,job: job).accept_application.deliver_now
  end

  def send_reject_mail
    user = User.find(self.user_id)
    job = self.job
    ConfirmationMailer.with(user: user,job: job).reject_application.deliver_now
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :jobs
end

app/models/client.rb
class Client < ApplicationRecord
  paginates_per 5
end

app/models/job.rb
class Job < ApplicationRecord
  paginates_per 5
  belongs_to :category
  belongs_to :user
  has_many :applies, dependent: :destroy
  has_many :applicants, through: :applies, dependent: :destroy
  validates :title, :description, :salary, :experience, :location,:skillset, presence: true
  validates :title, :description, :location,:skillset, length: {minimum: 10, message: "must be atleast 10 character long"}
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  validates :name, :email, :contact, :dob, :skills, :qualification, :address, presence: true
  validates :name, :skills, length: {minimum: 5}
  validates :contact, length: {:is => 10}
  validates :qualification, length: {minimum: 4}
  validates :address, length: {:in => 5..30}
end

app/models/user.rb
class User < ApplicationRecord
  after_initialize :default_role
  after_create :welcome_email
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :jobs, dependent: :destroy
  has_many :applies, dependent: :destroy
  has_many :applicants, through: :applies, dependent: :destroy
  has_one :profile, dependent: :destroy
  validates :name, presence: true
  
  def default_role
    self.role ||= :applicant
  end

  enum  :role, applicant: 'applicant', client: 'client', suffix: true

  def welcome_email
    ConfirmationMailer.welcome_email(self).deliver_now
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :after_sign_up
  
  rescue_from CanCan::AccessDenied do |exception|
    render json: {warning: exception, status: "Authorization failed"}
  end

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name,:email,:password,:role])
  end

  def after_sign_out_path_for(resource)
    new_user_session_path
  end

  def after_sign_in_path_for(resource)
    if current_user.client?
      client_path(id: current_user.id)
    else 
      jobs_path
    end
  end

  def after_sign_up
    if user_signed_in? && current_user.client?
      clients_url
    else 
      jobs_path
    end
  end
end

app/controllers/applies_controller.rb
class AppliesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_apply, only: [:accept, :reject, :show, :destroy]
  load_and_authorize_resource

  def index
    if current_user.applicant?
      @job_applications = current_user.applies.all.page(params[:page])
    else
      @applies = Apply.where(job_id: params[:job_id]).page(params[:page])
    end
  end

  def show
    @user = User.find(params[:user_id])
  end

  def new_apply
    @existing_apply = Apply.find_by(job_id: params[:job_id], user_id: current_user.id)
    if @existing_apply
      redirect_to root_path, alert: "You have already applied for this job."
    else
      @apply = Apply.new(job_id: params[:job_id], user_id: current_user.id)
      @apply.save
    end
  end

  def destroy
    @apply.destroy
    redirect_to root_path
  end

  def accept
    @apply.accepted!
    @apply.send_accept_mail
    redirect_to root_path
  end

  def reject
    @apply.rejected!
    @apply.send_reject_mail

  end

  private

  def find_apply
    @apply = Apply.find(params[:id])
  end
end

app/controllers/clients_controller.rb
class ClientsController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.where(role:'client')
  end

  def show
    @user = User.find(params[:id])
    @jobs = @user.jobs.all.page(params[:page])
  end
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:show, :edit, :update, :destroy]
  load_and_authorize_resource
  
  def index
    if params[:category].blank?
      @jobs = Job.all.page(params[:page])
    else
      @category_id = Category.find_by(name: params[:category]).id
      @jobs = Job.where(category_id: @category_id).page(params[:page])
    end
  end

  def show
  end

  def new
    @job = current_user.jobs.new
  end

  def create
    @job = current_user.jobs.new(job_params)
    if @job.save
      redirect_to @job
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @job.update(job_params)
      redirect_to @job
    else
      render :edit
    end
  end

  def destroy
    @job.destroy
    flash[:danger]= "Job deleted"
    redirect_to root_path
  end

  private

  def set_job
    @job = Job.find(params[:id])
  end

  def job_params
    params.require(:job).permit(:title,:description,:skillset,:salary,:experience,:location,:user_id,:category_id)
  end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :set_job, only: [:new, :edit]
  before_action :find_job, only: [:create, :update]
  before_action :find_profile, only: [:edit, :update]
  load_and_authorize_resource

  def new
    @profile = Profile.new
  end

  def create
    @profile = Profile.new(profile_params)
    if @profile.save!
      redirect_to new_application_path(job_id: @job.id)
    else
      render :new
    end
  end

  def edit
  end

  def update
    if @profile.update!(profile_params)
      redirect_to new_application_path(job_id: @job.id)
    else
      render :edit
    end
  end

  private

  def profile_params
    params.require(:profile).permit(:user_id,:name,:email,:contact,:dob,:qualification,:skills,:address)
  end

  def find_profile
    @profile = Profile.find(params[:id])
  end

  def find_job
    @job = Job.find(params[:profile][:job_id])
  end

  def set_job
    @job = Job.find(params[:job_id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applies_helper.rb
module AppliesHelper
end

app/helpers/clients_helper.rb
module ClientsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/views/applies/index.html.erb
<div id="jobs">
  <% if current_user.client? %>
    <h3>Total applications: <%= @applies.count %></h3>
    <% @applies.each do |application| %>
      <div class="job">
        <% user = User.find(application.user_id) %>
        <h2><%= link_to user.profile&.name, apply_path(id: application.id, user_id: user.id) %>
        </h2>
      </div>
    <% end %>
    <br>
    <%= paginate @applies %>
  <% else %>
    <% @job_applications.each do |application| %>
      <div class="job">
        <h2><%= application.job.title %></h2>
        <div class="button-group">
          <%= button_to "Delete application", apply_path(application.id), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-sm btn-default", style: "float: left; margin-right: 10px;" %>
          <%= button_tag application.status, class: "btn btn-sm btn-default", style: "float: left;" %>
        </div>
        <div style="clear: both;"></div>
      </div>
    <% end %>
    <br>
    <%= paginate @job_applications %>
  <% end %>
</div>

app/views/applies/new_apply.html.erb
<h2> Hi,<%= current_user.name%></h2>
<h3>Your job application for " <%=@apply.job.title %>" has been submitted successfully!<br><br>A Confirmation email has been sent to you, check your inbox</h3>
<div id='links'>
  <%= link_to  "Back", jobs_path,class:'btn btn-sm btn-default'%>
</div>

app/views/applies/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-6 offset-md-3">
      <div class="card">
        <div class="card-body">
          <h2 class="card-title mb-4" style="font-size: 28px; color: white;"><%= @user.profile.name %></h2>
          <h5 class="card-subtitle mb-4" style="font-size: 22px; color: black;"><%= @user.profile.email %></h5>
          <div>
            <p class="card-text mb-3" style="font-size: 20px; color: white;">
              <strong>Date of Birth:</strong>
              <span style="margin-left: 10px;"><%= @user.profile.dob %></span>
            </p>
          </div>
   
          <div>
            <p class="card-text mb-3" style="font-size: 20px; color: white;">
              <strong>Qualification:</strong> 
              <span style="margin-left: 10px;"><%= @user.profile.qualification %></p>
          </div>

          <div>
            <p class="card-text mb-3" style="font-size: 20px; color: white;"><strong>Skills:</strong>
            <span style="margin-left: 10px;"><%= @user.profile.skills %></p>
          </div>

          <div>
            <p class="card-text mb-3" style="font-size: 20px; color: white;"><strong>Address:</strong>
            <span style="margin-left: 10px;"><%= @user.profile.address %></p>
          </div>

          <div>
            <p class="card-text mb-4" style="font-size: 20px; color: white;"><strong>Contact:</strong> 
            <span style="margin-left: 10px;"><%= @user.profile.contact %></p>
          </div>
          <br>
          <%if @apply.status == 'accepted'%>
            <h3>You have already accepted this application</h3>
          <%elsif @apply.status == 'rejected'%>
            <h3>You have already rejected this application</h3>
          <%else%>
            <div class="mt-4">
              <%= link_to "Accept", accept_apply_path(id: @apply.id), method: :get, class: "btn btn-success btn-sm mr-2" %>
              <%= link_to "Reject", reject_apply_path(id: @apply.id), method: :get, class: "btn btn-danger btn-sm mr-2" %>
              <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
            </div>
          <%end%>
        </div>
      </div>
    </div>
  </div>
</div>
  

app/views/clients/index.html.erb
<h1>Our happy Clients</h1>
<ul>
  <% @users.each do |user|%>
    <li>
      <%= link_to user.email,client_path(user.id) %>
    </li>
  <% end %>
  </ul>
<br>
<% if user_signed_in? %>
  <%= link_to "Sign out", destroy_user_session_path %>
<% else %>
  <%= link_to "Sign In", new_user_session_path %>
<%end%>

app/views/clients/new.html.erb
<h1>New Client</h1>
<%= form_with model: @client do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :address %><br>
    <%= form.text_area :address %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/clients/show.html.erb
<div id="jobs">
  <% if @jobs.count != 0 %>
    <% @jobs.each do |job| %>
      <div class="job">
        <h2><%= link_to job.title, job_path(id: job.id) %></h2>
        <p><%= truncate(job.description, length: 50, omission: "...")%>,<%=link_to "Read More",job_path(id: job.id)%></p>
      </div>
    <% end %>
    <div id="links">
      <%= link_to "New Job", new_job_path, class: "btn btn-sm btn-default" %>
      <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
    </div>
  <% else %>
    <h2>You haven't posted any jobs</h2>
    <h3>Thought of something new? Create here</h3>
    <div id="links">
      <%= link_to "New Job", new_job_path, class: "btn btn-sm btn-default" %>
      <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
    </div>
  <% end %>
  <br>
  <%= paginate @jobs %>
</div>

app/views/jobs/edit.html.erb
<h1>Update Job</h1>

<%= form_with model: @job do |form| %>
  <div class="form-group">
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :skills %><br>
    <%= form.text_field :skillset, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :salary %><br>
    <%= form.text_field :salary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :experience %><br>
    <%= form.text_field :experience, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :location %><br>
    <%= form.text_area :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-sm btn-default" %>
    <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
  </div>
<% end %>

app/views/jobs/index.html.erb
<div id="jobs">
  <% @jobs.each do |job| %>
    <div class="job">
      <h2>
        <%= link_to job.title, job %>
      </h2>
      <p>
        <%= job.user.name %>
      </p>
    </div>
  <% end %>
  <br>
  <%= paginate @jobs %>
</div>

app/views/jobs/new.html.erb
<h1>New Job</h1>

<%= form_with model: @job do |form| %>
  <div class="form-group">
    <%= form.collection_select :category_id, Category.all, :id, :name, { prompt: "Choose a category" }, class: "form-control" %><br>
  </div>

  <div class="form-group">
    <%= form.label :title %><br>
    <%= form.text_field :title, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :description %><br>
    <%= form.text_area :description, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :skills %><br>
    <%= form.text_field :skillset, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :salary %><br>
    <%= form.text_field :salary, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :experience %><br>
    <%= form.text_field :experience, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :location %><br>
    <%= form.text_area :location, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-sm btn-default" %>
    <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
  </div>
<% end %>

app/views/jobs/show.html.erb
<div id="jobs">
  <div class="job">
    <h2><%= @job.title %></h2>
    <h3><%= @job.user.name %></h3>
    <p><%= @job.user.email %></p>
    <p><%= @job.description %></p>
    <p><strong>Skills:</strong> <%= @job.skillset %></p>
    <p><strong>Salary:</strong> <%= @job.salary %></p>
    <p><strong>Experience:</strong> <%= @job.experience %></p>
    <p><strong>Location:</strong> <%= @job.location %></p>
    <% if current_user.applicant? %>
      <% if current_user.profile.present? %>
        <% if @job.applicants.where(id: current_user.id).present? %>
          <h3>You have already applied for this job</h3>
        <% else %>
          <h3>You have already created a profile</h3>
          <div class="btn-group">
            <%= link_to "Update profile", edit_profile_path(id: current_user.profile.id, job_id: @job.id), class: "btn btn-primary" %>
            <%= link_to "Apply with same profile", new_application_path(job_id: @job.id), class: "btn btn-primary" %>
          </div>
        <% end %>
      <% else %>
        <div class="btn-group">
          <%= link_to "Apply for Job", new_profile_path(job_id: @job.id), class: "btn btn-primary" %>
          <%= link_to "Back", root_path, class: "btn btn-default" %>
        </div>
      <% end %>
    <% end %>
  </div>
</div>
<div id="links">
  <%= link_to "Back", root_path, class: "btn btn-sm btn-default" %>
  <% if current_user.client? && (@job.user.id == current_user.id) %>
    <%= link_to "Edit", edit_job_path(id: @job), class: "btn btn-sm btn-default" %>
    <%= link_to "All applications", applies_url(user_id: current_user.id, job_id: @job.id), class: "btn btn-sm btn-default" %>
    <br><br>
    <%= button_to "Delete job", job_path(id: @job), method: :delete, data: { confirm: "Are you sure?" }, class: "btn btn-danger" %>
  <% end %>
</div>
<style>
  .btn-group {
    display: flex;
    gap: 10px;
  }
</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CareerLink</title>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
  <style>
    .navbar {
      background-color: #f8f9fa;
      widht: 100%;
      padding: 10px;
    }
    
    .navbar-brand {
      font-size: 40px;
      font-weight: bold;
      color: #1D976C !important;
      text-transform: camelcase;
      margin-right: 20px;
      margin-left: 0px
    }
    
    .navbar-nav li {
      margin-right: 20px;
    }

    .navbar-nav li:not(:last-child) {
      margin-right: 40px; /* Add space between list items */
    }
    
    .navbar-nav li a {
      font-size: 18px;
      color: #333;
    }
    
    .navbar-nav li a:hover {
      color: #007bff;
    }
    
    .nav-link.btn {
      font-size: 18px;
    }

    .sign-out-btn {
      position: absolute;
      top: 19px;
      right: 30px;
    }
  </style>
</head>
<body>
  <% if user_signed_in? %>
    <nav class="navbar navbar-expand-lg navbar-default">
      <div class="container d-flex align-items-center justify-content-between">
        <div class="navbar-brand">CareerLink</div>
            <ul class="nav navbar-nav custom-navbar">
              <li>
                <%= link_to "All Jobs", jobs_path %>
              </li>
              <li>
                <% if user_signed_in? && current_user.client? %>
                  <%= link_to "My Jobs", client_path(id: current_user.id), class: "nav-link" %>
                <% elsif user_signed_in? %>
                  <%= link_to "My Applications", applies_url, class: "nav-link" %>
                <% end %>
              </li>
              <% Category.all.each do |category| %>
                <li>
                  <%= link_to category.name, jobs_path(category: category.name), class: "nav-link" %>
                </li>
              <% end %>
            </ul>
        <div class="sign-out-btn">
          <% if user_signed_in? %>
            <%= link_to "Edit profile", edit_user_registration_path(current_user), class: "btn btn-primary" %>
            <%= link_to "Sign Out", destroy_user_session_path, class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </nav>
  <% else %>
    <% new_user_session_path %>
  <%end%>
  <div class="container">
    <div class="col-md-6 col-md-offset-3">
      <%= yield %>
    </div>
  </div>
</body>
</html>

app/views/profiles/edit.html.erb
<h1>Update your profile</h1>

<%= form_with model: @profile do |form| %>
  <%= form.hidden_field :job_id, value: @job.id %>
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.label :full_name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :contact %><br>
    <%= form.text_field :contact, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :dob, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :qualification %><br>
    <%= form.text_field :qualification, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :skills %><br>
    <%= form.text_field :skills, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %><br>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/profiles/new.html.erb
<h1>Create your profile</h1>

<%= form_with model: @profile do |form| %>
  <%= form.hidden_field :job_id, value: @job.id %>
  <div class="form-group">
    <%= form.hidden_field :user_id, value: current_user.id %>
    <%= form.label :full_name %><br>
    <%= form.text_field :name, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :email %><br>
    <%= form.email_field :email, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :contact %><br>
    <%= form.text_field :contact, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :date_of_birth %><br>
    <%= form.date_field :dob, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :qualification %><br>
    <%= form.text_field :qualification, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :skills %><br>
    <%= form.text_field :skills, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.label :address %><br>
    <%= form.text_area :address, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= form.submit class: "btn btn-primary" %>
  </div>
<% end %>